# 8. 이미지 분류

### 8.1 합성곱

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
w = np.array([2 ,1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [4]:
w_r = np.flip(w)
print(w_r)

[3 5 1 2]


 슬라이싱의 형식을 다시 기억해 봅시다:

- start: 시작 인덱스
- stop: 종료 인덱스 (이 인덱스는 포함되지 않음)
- step: 선택한 원소 간의 간격
- w[0:4:2]를 해석하면 다음과 같습니다:

- 시작 인덱스: 0
- 종료 인덱스: 4 (4는 포함되지 않음)
- 간격: 2

In [5]:
w[0:4:2]

array([2, 5])

In [6]:
for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [7]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [8]:
from scipy.signal import convolve

In [9]:
convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [10]:
from scipy.signal import correlate

In [11]:
correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

In [12]:
correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [13]:
correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [14]:
x = np.array([[1 ,2, 3],
              [4, 5, 6],
              [7, 8, 9]])

w = np.array([[2, 0], [0, 0]])

In [15]:
from scipy.signal import correlate2d

correlate2d(x, w, mode='valid') # 각 커널의 상관관계를 나타냄

array([[ 2,  4],
       [ 8, 10]])

In [16]:
np.flip(w)

array([[0, 0],
       [0, 2]])

In [17]:
from scipy.signal import convolve2d

convolve2d(x, w, mode='valid')

array([[10, 12],
       [16, 18]])

In [18]:
correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [20]:
import tensorflow as tf

In [21]:
x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')
c_out.numpy().reshape(3, 3)

NameError: name 'x_4d' is not defined